<section id="site-content" class="clear">
	<p>
		Computer technology is becoming more efficient, productive, and cheaper. Advances in technology are producing more powerful computing devices to create a dynamic virtual network that allows people all over the world to communicate and share information with each other. The growth and importance of the technology and the virtual network are underscored by two important laws. First is Moore’s Law, which states that “integrated circuit technology advancements would enable the semiconductor industry to double the number of components on every chip 18 to 24 months” (Coyle, 2009, p. 559). Essentially, this means that the speed and productivity of a computer increases two-fold every 1.5 to 2 years. While such growth may not be sustained indefinitely, the exponential growth of technology realized thus far has reshaped our society and will continue to be a dynamic force in future generations. It is important that social workers understand the role that technology plays in shaping the lives of clients and the services that are delivered. The second law, Metcalfe’s Law, states “the value of a network increases in proportion to the square of the number of people connected to the network” (Coyle, 2009, p. 559). These rapidly developing technologies, and the individuals that utilize them, are producing virtual networks of greater size and value.

		At the time Granovetter published his classic study on networks and employment (Granovetter, 1973), ICTs played almost no role in developing and maintaining network relationships. Today, Internet sites such as LinkedIn (www.linkedin.com) produce vast social networks that provide opportunities for professionals and employers to advertise and communicate. To effectively use social networks, whether for obtaining employment, securing resources, or obtaining information, social workers need to understand the capabilities of these networks, and how they can be effectively understood, managed, and utilized within a digital environment.
	</p>
	<p>
		Computer technology is becoming more efficient, productive, and cheaper. Advances in technology are producing more powerful computing devices to create a dynamic virtual network that allows people all over the world to communicate and share information with each other. The growth and importance of the technology and the virtual network are underscored by two important laws. First is Moore’s Law, which states that “integrated circuit technology advancements would enable the semiconductor industry to double the number of components on every chip 18 to 24 months” (Coyle, 2009, p. 559). Essentially, this means that the speed and productivity of a computer increases two-fold every 1.5 to 2 years. While such growth may not be sustained indefinitely, the exponential growth of technology realized thus far has reshaped our society and will continue to be a dynamic force in future generations. It is important that social workers understand the role that technology plays in shaping the lives of clients and the services that are delivered. The second law, Metcalfe’s Law, states “the value of a network increases in proportion to the square of the number of people connected to the network” (Coyle, 2009, p. 559). These rapidly developing technologies, and the individuals that utilize them, are producing virtual networks of greater size and value.

		At the time Granovetter published his classic study on networks and employment (Granovetter, 1973), ICTs played almost no role in developing and maintaining network relationships. Today, Internet sites such as LinkedIn (www.linkedin.com) produce vast social networks that provide opportunities for professionals and employers to advertise and communicate. To effectively use social networks, whether for obtaining employment, securing resources, or obtaining information, social workers need to understand the capabilities of these networks, and how they can be effectively understood, managed, and utilized within a digital environment.
	</p>
</section>


